// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IGiftCardController is an autogenerated mock type for the IGiftCardController type
type IGiftCardController struct {
	mock.Mock
}

// AddGiftCard provides a mock function with given fields: ctx
func (_m *IGiftCardController) AddGiftCard(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetReceivedGiftCards provides a mock function with given fields: ctx
func (_m *IGiftCardController) GetReceivedGiftCards(ctx *gin.Context) {
	_m.Called(ctx)
}

// SendGiftCard provides a mock function with given fields: ctx
func (_m *IGiftCardController) SendGiftCard(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateGiftCardStatus provides a mock function with given fields: ctx
func (_m *IGiftCardController) UpdateGiftCardStatus(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewIGiftCardController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIGiftCardController creates a new instance of IGiftCardController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIGiftCardController(t mockConstructorTestingTNewIGiftCardController) *IGiftCardController {
	mock := &IGiftCardController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
